apiVersion: v1
kind: Service
metadata:
  name: jkpgcitywebsite-service
  namespace: jkpgcity
spec:
  selector:
    app: jkpgcitywebsite
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
